### ISSUE TITLE
Building container STEP 28/33 fails with gunzip: invalid magic

### ISSUE THREAD

**Issue by Tw3aky81** [XoruX/lpar2rrd#2]
Hi, 
I'm trying to build the lpar2rrd container from source and it seems that for me it fails at step 28/33 and exits with an error saying  `gunzip: invalid magic`. 

Some digging through the Dockerfile thought me that on line
``` 
104   ADD https://lpar2rrd.com/agent/lpar2rrd-agent.pl.gz /opt/lpar2rrd-agent/ 
```
downloads the `lpar2rrd-agent-pl.gz` file, but the content is not what it is expecting as we will see later on. The build continues at this point, though.

Then, on line 
```
109   RUN gunzip /opt/lpar2rrd-agent/lpar2rrd-agent.pl.gz && chmod +r /opt/lpar2rrd-agent/lpar2rrd-agent.pl
```
it tries to unzip the `lpar2rrd-agent.pl.gz` file, but gives an error and the build fails
```
gunzip: invalid magic
```

Inspection of the file showed me, the file is actually containing the html from the page on the website. Not any type of archive file. The url https://lpar2rrd.com/agent/lpar2rrd-agent.pl.gz currently points to a customised 404 page for the domain.

I'd like to try and replace the url to add that agent file in from, but I just can't find it on the site anymore.
What was in that script when it would've been pulling in the `lpar2rrd-agent.pl` file and/or is there an alternative location where to pull this file from?

Thanks in advance

**Comment by goricz** [comment]
Hello, 

LPAR2RRD agent is now distributed as rpm/deb package only, it's fixed in 
https://github.com/XoruX/lpar2rrd/commit/f261f25825e8f8a6f539548a308ec070fceaf9c6

**Comment by Tw3aky81** [comment]
Ok, that explains a lot. :)
I guess when building on a non dpkg system (ie not a debian distro), I guess I'll need to pull the rpm's and install with rpm.
EDIT: talking non-sense... you're adding dpkg in container, so shouldn't be a problem to pull deb file.

Thanks for the :zap: lightning quick respons.

**Comment by Tw3aky81** [comment]
Ok, verified. The build now works.
Thanks
